/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mobileprocurementapplication;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ShavinPC
 */
public class UpdateUserUI extends javax.swing.JFrame {

    /**
     * Creates new form UpdateUserUI
     */
    
    private static final String UserFile = "User.ser";
    private SetOfUsers<User> userList = new SetOfUsers();
    private UserService userService;
    
    public static String Username;
    public static int UserID; 
    
    public UpdateUserUI(int userID, String userName) {
        initComponents();
        
        //Setting the username
        Username = userName;
        
        //Setting the userID 
        UserID = userID;
        
        //Setting the initial position of the window to center
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
        userService = new UserService();
        
        try {
            userList = this.userService.Deserialize(UserFile);
        } catch (IOException ex) {
            Logger.getLogger(UpdateUserUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(UpdateUserUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        for(User aUser : userList)
        {
            if(aUser.getUserID() == UserID)
            {
                txtFullName.setText(aUser.getUserFullName());
                txtTelephoneNumber.setText(aUser.getTelephoneNumber());
                txtUsername.setText(aUser.getUsername());
                
                if(aUser.getUserType().equals("Site Manager"))
                {
                    cmbUserType.setSelectedIndex(0);
                }
                else if(aUser.getUserType().equals("Accountant"))
                {
                    cmbUserType.setSelectedIndex(1);
                }
                else if(aUser.getUserType().equals("Manager"))
                {
                    cmbUserType.setSelectedIndex(2);
                }     
                
                break;
            }           
        }
        
        disableInterface();
                
    }
    
    public void enableInterface()
    {
        txtFullName.setEnabled(true);
        txtTelephoneNumber.setEnabled(true);
        txtUsername.setEnabled(true);
        cmbUserType.setEnabled(true);
        btnUpdateUser.setEnabled(true);
    }
    
    public void disableInterface()
    {
        txtFullName.setEnabled(false);
        txtTelephoneNumber.setEnabled(false);
        txtUsername.setEnabled(false);
        cmbUserType.setEnabled(false);
        btnUpdateUser.setEnabled(false);
    }

    private UpdateUserUI() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUpdateUser = new javax.swing.JButton();
        cmbUserType = new javax.swing.JComboBox();
        txtUsername = new javax.swing.JTextField();
        txtTelephoneNumber = new javax.swing.JTextField();
        txtFullName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnMakeEditable = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Update User");

        btnUpdateUser.setText("Update User");
        btnUpdateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateUserActionPerformed(evt);
            }
        });

        cmbUserType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Site Manager", "Accountant", "Manager" }));
        cmbUserType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbUserTypeActionPerformed(evt);
            }
        });

        txtUsername.setEditable(false);

        jLabel6.setText("User Type");

        jLabel4.setText("Username");

        jLabel3.setText("Telephone Number");

        jLabel2.setText("Full Name");

        btnMakeEditable.setText("Make Editable");
        btnMakeEditable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakeEditableActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUpdateUser)
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbUserType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                            .addComponent(txtTelephoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                            .addComponent(txtFullName)))
                    .addComponent(btnMakeEditable)
                    .addComponent(btnBack))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnMakeEditable)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTelephoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbUserType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnUpdateUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateUserActionPerformed

        //Updating the user

        if(txtFullName.getText().equals("") || txtTelephoneNumber.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please fill all text boxes!", null, JOptionPane.ERROR_MESSAGE);
        }        
        else
        {
                        
            for(User aUser : userList)
            {
                if(aUser.getUserID() == UserID)
                {
                    User updatedUser = new User (UserID, txtFullName.getText(), txtTelephoneNumber.getText(), txtUsername.getText(), aUser.getPassword(), cmbUserType.getSelectedItem().toString());
                    userList.remove(aUser);
                    
                    try {
                        this.userService.Serialize(userList, UserFile);
                    } catch (IOException ex) {
                        Logger.getLogger(UpdateUserUI.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                    userList.add(updatedUser);
                    
                    try {
                        this.userService.Serialize(userList, UserFile);
                        JOptionPane.showMessageDialog(null, "User Successfully Update", null, JOptionPane.INFORMATION_MESSAGE);                         
                        disableInterface();
                    } catch (IOException ex) {
                        Logger.getLogger(UpdateUserUI.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                    break;
                }
            }      

        }

    }//GEN-LAST:event_btnUpdateUserActionPerformed

    private void cmbUserTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUserTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbUserTypeActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        
        MainUI mui = new MainUI(Username);
        this.dispose();
        mui.setVisible(true);
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnMakeEditableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakeEditableActionPerformed
        enableInterface();
    }//GEN-LAST:event_btnMakeEditableActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateUserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateUserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateUserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateUserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateUserUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnMakeEditable;
    private javax.swing.JButton btnUpdateUser;
    private javax.swing.JComboBox cmbUserType;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtTelephoneNumber;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
